### ISSUE TITLE
Inconsistent rounding

### ISSUE THREAD

**Issue by pdamoc** [ggb/numeral-elm#7] opened 2016-07-20 16:20 UTC
I'm seeing an inconsistent rounding problem: 

`format "0,0.00" 2.385` == `"2.38"` but shouldn't it be `"2.39"` ?
for example 
`format "0,0.00" 28.885` == `"28.89"`

**Comment by ggb** [comment] 2016-07-20 19:34
Hi Petre,

numeral.js seems to have the same inconsistency and I think it is caused by floating point arithmetic: To round the significant figures the input number is multiplied by 10^precision, rounded and divided by 10^precision; multiplying goes kind of wrong...
`2.385 * 100  => 238.49999999999997`, but
`28.885 * 100 => 2888.5`

I've found a simple fix for this problem and will republish the package soon.

Thanks,
Gregor

**Closed as completed by ggb** 2016-07-20 19:34 UTC

**Comment by pdamoc** [comment] 2016-07-20 19:36
wonderful! Thank you!
